# Generated by Django 4.1.2 on 2022-10-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_naturalprofile_first_name_and_more'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.fund')),
                ('legal_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.legalprofile')),
                ('natural_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.naturalprofile')),
            ],
        ),
    ]
