# Generated by Django 4.1.2 on 2022-10-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_subscription_legal_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'fund', 'verbose_name_plural': 'funds'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
    ]
