# Generated by Django 4.1.3 on 2022-11-03 17:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_fund_closing_date_fund_goal_fund_goal_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=django_fsm.FSMField(choices=[('being created', 'Being created'),
                                               ('published', 'Published'),
                                               ('closed', 'Closed')],
                                      default='being created',
                                      max_length=50),
        ),
    ]
