# Generated by Django 4.1.2 on 2022-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_legalprofile_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='profile_ptr',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='natural',
            name='profile_ptr',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
    ]
