# Generated by Django 4.1.2 on 2022-10-19 07:17

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def forwards(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    LegalProfile = apps.get_model('accounts', 'Legal')
    NaturalProfile = apps.get_model('accounts', 'Natural')
    legal_content_type = ContentType.objects.get_for_model(LegalProfile)
    natural_content_type = ContentType.objects.get_for_model(NaturalProfile)

    for child in LegalProfile.objects.all():
        parent = Profile.objects.create(
            user=child.user,
            phone_number=child.phone_number,
            polymorphic_ctype_id=legal_content_type.id
        )
        child.profile_ptr = parent.pk
        child.save()
    for child in NaturalProfile.objects.all():
        parent = Profile.objects.create(
            user=child.user,
            phone_number=child.phone_number,
            polymorphic_ctype_id=natural_content_type.id
        )
        child.profile_ptr = parent.pk
        child.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_legal_profile_ptr_natural_profile_ptr'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
