# Generated by Django 4.1.2 on 2022-10-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_build_profile_parent_rows_and_associate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='natural',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='legal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='natural',
            name='id',
        ),
        migrations.RemoveField(
            model_name='natural',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='natural',
            name='user',
        ),
        migrations.AlterField(
            model_name='legal',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='natural',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile'),
        ),
    ]
