# Generated by Django 4.1.2 on 2022-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_legal_options_alter_natural_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'legal entity', 'verbose_name_plural': 'legal entities'},
        ),
        migrations.AlterModelOptions(
            name='natural',
            options={'verbose_name': 'natural person', 'verbose_name_plural': 'natural persons'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
