# Generated by Django 4.1.3 on 2022-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_legal_options_alter_natural_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='old@re.cord', max_length=254),
            preserve_default=False,
        ),
    ]
