# Generated by Django 4.1.4 on 2022-12-15 13:52

import accounts.validators.file_size
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='accounts/profiles/avatars/',
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg']),
                    accounts.validators.file_size.FileSizeValidator(1048576)
                ]
            ),
        ),
    ]
